### PR TITLE
Branches/issue34

### PR DESCRIPTION
**Pull request by cmikk**
Check for the existence of `pthread_condattr_setclock` in addition to `clock_gettime`.

### CODE REVIEW

**Comment by edmonds** [comment]
I'm kinda confused by this. Why should the existence of `clock_gettime` be conditional on `pthread_condattr_setclock`? That prevents any non- `pthread_cond_timedwait()` related uses of `clock_gettime`, e.g. in `fstrm__iothr_maybe_open()`.

**Comment by cmikk** [comment]
@edmonds -  I had missed those uses of `clock_gettime()` in my review.

The core issue is that `HAVE_CLOCK_GETTIME` presumes `pthread_condattr_setclock()` exists, which is not necessarily the case. I've pushed a more correct fix to the branch head.

**Comment by edmonds** [comment]
@cmikk I think the `#ifdef` in `fstrm__iothr_thr()` also needs an `&& HAVE_PTHREAD_CONDATTR_SETCLOCK`?

https://github.com/farsightsec/fstrm/blob/v0.3.1/fstrm/iothr.c#L614-L623

**Comment by cmikk** [comment]
Agreed, and fixed.

**Comment by reedjc** [comment]
AC_CHECK_FUNCS([clock_gettime, pthread_condattr_setclock])

is broken. See the comma in the functions list. The configure output shows it too and the config.out shows errors like 
```
#undef clock_gettime,
                    ^
                    //
conftest.c:52:22: error: expected identifier or '('
```

**Comment by cmikk** [comment]
The typo @reedjc pointed out made the builds (and checks) work by disabling `clock_gettime()` entirely. Correcting the typo exposed an error in the `#ifdef` fix, which required a different choice of default clock for `clock_gettime()`.

My research indicated that, if `pthread_condattr_setclock()` is not available to say otherwise, `pthread_cond_timedwait()` uses `CLOCK_REALTIME` by default. I amended the `#ifdef` fix to do so if `clock_gettime()` is available but `pthread_condattr_setclock()` is not, squashed in a fix to the erroneous ',' in configure.ac, and pushed a relatively clean branch to replace the old `branches/issue34`.

**Pull request merged**
